export MONGO_HOST="localhost"
export MONGO_PORT="5432"
export MONGO_ADMIN_USER="postrges"
export MONGOPASSWORD="xxxxx"
export AWS_ACCESS_KEY="xxxxx"
export AWS_SECRET_KEY="xxxxx"
export AWS_DEFAULT_REGION="ap-south-1"
export BUCKET_NAME="bucket/path"